"""Plan Validator for Phase 3 Agent.

Validates agent output to ensure safety and correctness.
"""

from typing import Dict, Any, Optional, List
from app.agent.schemas import RecoveryPlan, ActionType, AgentAction
from app.agent.strategies.registry import ActionRegistry
from app.core.logging import get_logger

logger = get_logger(__name__)


class PlanValidator:
    """Validates recovery plans generated by the agent."""
    
    def validate_plan(self, plan_data: Dict[str, Any]) -> tuple[bool, Optional[str], Optional[RecoveryPlan]]:
        """Validate a plan and convert to RecoveryPlan schema.
        
        Returns:
            (is_valid, error_message, recovery_plan)
        """
        try:
            # Check required fields
            required_fields = [
                "summary",
                "diagnosis",
                "selected_strategy",
                "reasoning",
                "confidence",
                "proposed_actions",
                "fallback_strategy",
                "requires_approval",
            ]
            
            for field in required_fields:
                if field not in plan_data:
                    return False, f"Missing required field: {field}", None
            
            # Validate selected strategy
            selected_strategy = plan_data["selected_strategy"]
            if not ActionRegistry.is_action_allowed(selected_strategy):
                return False, f"Invalid action type: {selected_strategy}", None
            
            # Validate confidence
            confidence = plan_data["confidence"]
            if not isinstance(confidence, (int, float)) or not (0.0 <= confidence <= 1.0):
                return False, f"Invalid confidence: {confidence}", None
            
            # Validate proposed actions
            proposed_actions = plan_data.get("proposed_actions", [])
            validated_actions = []
            
            for action_data in proposed_actions:
                is_valid, error, action = self._validate_action(action_data)
                if not is_valid:
                    return False, f"Invalid action: {error}", None
                validated_actions.append(action)
            
            # Construct RecoveryPlan
            plan = RecoveryPlan(
                opportunity_id=plan_data.get("opportunity_id", ""),
                payment_id=plan_data.get("payment_id", ""),
                merchant_id=plan_data.get("merchant_id", ""),
                summary=plan_data["summary"],
                diagnosis=plan_data["diagnosis"],
                selected_strategy=ActionType(selected_strategy),
                reasoning=plan_data["reasoning"],
                confidence=confidence,
                proposed_actions=validated_actions,
                alternatives_considered=plan_data.get("alternatives_considered", []),
                required_inputs=plan_data.get("required_inputs", []),
                risks=plan_data.get("risks", []),
                constraints=plan_data.get("constraints", []),
                fallback_strategy=plan_data["fallback_strategy"],
                requires_approval=plan_data["requires_approval"],
                policy_status=plan_data.get("policy_status", "UNKNOWN"),
            )
            
            return True, None, plan
            
        except Exception as e:
            logger.error(f"Plan validation error: {e}")
            return False, f"Validation failed: {str(e)}", None
    
    def _validate_action(self, action_data: Dict[str, Any]) -> tuple[bool, Optional[str], Optional[AgentAction]]:
        """Validate a single action."""
        try:
            # Check required fields
            required_fields = ["action_type", "purpose", "rationale", "expected_outcome"]
            for field in required_fields:
                if field not in action_data:
                    return False, f"Missing required field: {field}", None
            
            # Validate action type
            action_type_str = action_data["action_type"]
            if not ActionRegistry.is_action_allowed(action_type_str):
                return False, f"Invalid action type: {action_type_str}", None
            
            # Validate parameters against schema
            action_type = ActionType(action_type_str)
            parameters = action_data.get("parameters", {})
            
            if not ActionRegistry.validate_action_parameters(action_type, parameters):
                return False, f"Invalid parameters for action {action_type}", None
            
            # Construct AgentAction
            action = AgentAction(
                action_type=action_type,
                purpose=action_data["purpose"],
                parameters=parameters,
                rationale=action_data["rationale"],
                expected_outcome=action_data["expected_outcome"],
                risk_level=action_data.get("risk_level", "LOW"),
                requires_approval=action_data.get("requires_approval", False),
            )
            
            return True, None, action
            
        except Exception as e:
            logger.error(f"Action validation error: {e}")
            return False, f"Action validation failed: {str(e)}", None
    
    def sanitize_untrusted_data(self, data: str) -> str:
        """Sanitize untrusted data to prevent prompt injection."""
        # Remove potential instruction injection patterns
        dangerous_patterns = [
            "ignore all previous instructions",
            "ignore previous instructions",
            "forget all instructions",
            "system:",
            "assistant:",
            "user:",
            "<system>",
            "</system>",
        ]
        
        sanitized = data.lower()
        for pattern in dangerous_patterns:
            if pattern in sanitized:
                logger.warning(f"Detected potential prompt injection: {pattern}")
                return "[SANITIZED: Potential injection detected]"
        
        return data
