"""Pydantic schemas for AI Recovery Agent - Phase 3."""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
from uuid import UUID, uuid4


class PolicyStatus(str, Enum):
    """Policy validation status."""
    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"


class AgentRunStatus(str, Enum):
    """Agent run status."""
    CREATED = "CREATED"
    INVESTIGATING = "INVESTIGATING"
    PLANNING = "PLANNING"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


class RiskLevel(str, Enum):
    """Risk level for proposed actions."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ActionType(str, Enum):
    """Allowed recovery actions."""
    RETRY_PAYMENT = "RETRY_PAYMENT"
    REQUEST_ALTERNATE_PAYMENT_METHOD = "REQUEST_ALTERNATE_PAYMENT_METHOD"
    SEND_PAYMENT_REMINDER = "SEND_PAYMENT_REMINDER"
    REQUEST_REAUTHENTICATION = "REQUEST_REAUTHENTICATION"
    WAIT_AND_RETRY = "WAIT_AND_RETRY"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    CLOSE_RECOVERY_CASE = "CLOSE_RECOVERY_CASE"
    ESCALATE = "ESCALATE"


class AgentAction(BaseModel):
    """A proposed action in the recovery plan."""
    action_type: ActionType = Field(..., description="Type of action to take")
    purpose: str = Field(..., description="Purpose of this action")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Action parameters")
    rationale: str = Field(..., description="Why this action is appropriate")
    expected_outcome: str = Field(..., description="Expected result of this action")
    risk_level: RiskLevel = Field(default=RiskLevel.LOW, description="Risk level of this action")
    requires_approval: bool = Field(default=False, description="Whether this action requires approval")


class DecisionTrace(BaseModel):
    """Safe decision trace (not chain-of-thought)."""
    observation: str = Field(..., description="What the agent observed")
    evidence: str = Field(..., description="Evidence supporting the decision")
    decision: str = Field(..., description="Decision made")
    reason: str = Field(..., description="Reason for the decision")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in this decision")


class AgentContext(BaseModel):
    """Context provided to the agent for reasoning."""
    # Payment context
    payment_id: str
    payment_amount: int
    payment_currency: str
    payment_status: str
    payment_method: Optional[str] = None
    failure_category: Optional[str] = None
    failure_reason: Optional[str] = None
    failure_code: Optional[str] = None
    retry_count: int = 0
    created_at: datetime
    
    # Phase 2 intelligence
    revenue_at_risk: int
    recovery_likelihood: float
    opportunity_score: float
    priority: str
    recommended_intervention: Optional[str] = None
    contributing_factors: List[Dict[str, Any]] = Field(default_factory=list)
    
    # Recovery history
    previous_recovery_attempts: int = 0
    previous_successful_recovery: bool = False
    previous_failed_recovery: bool = False
    last_action: Optional[str] = None
    time_since_last_attempt_hours: Optional[float] = None
    
    # Merchant context
    merchant_id: str
    merchant_name: str
    historical_recovery_rate: float = 0.0
    avg_transaction_value: int = 0
    
    # System context
    allowed_actions: List[str] = Field(default_factory=list)
    action_limits: Dict[str, Any] = Field(default_factory=dict)
    approval_requirements: Dict[str, bool] = Field(default_factory=dict)
    current_system_state: str = "OPERATIONAL"


class RecoveryPlan(BaseModel):
    """Structured recovery plan generated by the agent."""
    plan_id: str = Field(default_factory=lambda: str(uuid4()))
    opportunity_id: str
    payment_id: str
    merchant_id: str
    
    # Summary
    summary: str = Field(..., description="Brief summary of the plan")
    diagnosis: str = Field(..., description="Diagnosis of what happened and why")
    
    # Strategy
    selected_strategy: ActionType = Field(..., description="Selected recovery strategy")
    reasoning: str = Field(..., description="Why this strategy was selected")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Agent confidence in this plan")
    
    # Actions
    proposed_actions: List[AgentAction] = Field(default_factory=list, description="Proposed actions in sequence")
    
    # Alternatives
    alternatives_considered: List[Dict[str, str]] = Field(default_factory=list, description="Alternative strategies and why they were rejected")
    
    # Safety
    required_inputs: List[str] = Field(default_factory=list, description="Inputs required for execution")
    risks: List[str] = Field(default_factory=list, description="Identified risks")
    constraints: List[str] = Field(default_factory=list, description="Constraints on execution")
    fallback_strategy: str = Field(..., description="Fallback strategy if primary fails")
    requires_approval: bool = Field(default=False, description="Whether the plan requires approval")
    
    # Policy validation
    policy_status: PolicyStatus = Field(..., description="Policy validation result")
    policy_reason: Optional[str] = Field(None, description="Reason for policy decision")
    
    # Metadata
    agent_version: str = "agent-v1"
    prompt_version: str = "recovery-prompt-v1"
    policy_version: str = "policy-v1"
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        from_attributes = True


class AgentState(BaseModel):
    """Agent execution state."""
    run_id: str = Field(default_factory=lambda: str(uuid4()))
    opportunity_id: str
    payment_id: str
    merchant_id: str
    
    # Execution state
    current_step: int = 0
    status: AgentRunStatus = AgentRunStatus.CREATED
    
    # Context
    context: Optional[AgentContext] = None
    
    # Tool calls
    tool_calls: List[Dict[str, Any]] = Field(default_factory=list)
    
    # Reasoning
    reasoning_summary: Optional[str] = None
    decision_trace: List[DecisionTrace] = Field(default_factory=list)
    
    # Output
    proposed_plan: Optional[RecoveryPlan] = None
    
    # Validation
    validation_result: Optional[Dict[str, Any]] = None
    
    # Error handling
    errors: List[str] = Field(default_factory=list)
    
    # Timing
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    
    # Metadata
    agent_version: str = "agent-v1"
    prompt_version: str = "recovery-prompt-v1"
    policy_version: str = "policy-v1"


class ToolCall(BaseModel):
    """Record of a tool call made by the agent."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    run_id: str
    tool_name: str
    input_summary: str
    output_summary: str
    step_number: int
    execution_time_ms: int
    created_at: datetime = Field(default_factory=datetime.utcnow)


class AgentRunRequest(BaseModel):
    """Request to run the agent on an opportunity."""
    opportunity_id: Optional[str] = None
    force_reanalyze: bool = False


class AgentRunResponse(BaseModel):
    """Response from agent run."""
    run_id: str
    status: AgentRunStatus
    selected_strategy: Optional[str] = None
    confidence: Optional[float] = None
    plan: Optional[RecoveryPlan] = None
    decision_summary: Optional[str] = None
    policy_status: Optional[PolicyStatus] = None
    error: Optional[str] = None
